/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as SosRouteImport } from './routes/sos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoRouteImport } from './routes/mo'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIdRouteImport } from './routes/report.$id'
import { Route as PharmacyIdRouteImport } from './routes/pharmacy.$id'
import { Route as MoIdRouteImport } from './routes/mo.$id'
import { Route as CheckinTokenRouteImport } from './routes/checkin.$token'

const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoRoute = MoRouteImport.update({
  id: '/mo',
  path: '/mo',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIdRoute = ReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIdRoute = PharmacyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PharmacyRoute,
} as any)
const MoIdRoute = MoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MoRoute,
} as any)
const CheckinTokenRoute = CheckinTokenRouteImport.update({
  id: '/checkin/$token',
  path: '/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/consultation': typeof ConsultationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/mo': typeof MoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sos': typeof SosRoute
  '/visits': typeof VisitsRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/mo/$id': typeof MoIdRoute
  '/pharmacy/$id': typeof PharmacyIdRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/consultation': typeof ConsultationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/mo': typeof MoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sos': typeof SosRoute
  '/visits': typeof VisitsRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/mo/$id': typeof MoIdRoute
  '/pharmacy/$id': typeof PharmacyIdRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRoute
  '/consultation': typeof ConsultationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/mo': typeof MoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pharmacy': typeof PharmacyRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sos': typeof SosRoute
  '/visits': typeof VisitsRoute
  '/checkin/$token': typeof CheckinTokenRoute
  '/mo/$id': typeof MoIdRoute
  '/pharmacy/$id': typeof PharmacyIdRoute
  '/report/$id': typeof ReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clinics'
    | '/consultation'
    | '/forgot-password'
    | '/heatmap'
    | '/login'
    | '/medications'
    | '/mo'
    | '/onboarding'
    | '/pharmacy'
    | '/profile'
    | '/reset-password'
    | '/sos'
    | '/visits'
    | '/checkin/$token'
    | '/mo/$id'
    | '/pharmacy/$id'
    | '/report/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clinics'
    | '/consultation'
    | '/forgot-password'
    | '/heatmap'
    | '/login'
    | '/medications'
    | '/mo'
    | '/onboarding'
    | '/pharmacy'
    | '/profile'
    | '/reset-password'
    | '/sos'
    | '/visits'
    | '/checkin/$token'
    | '/mo/$id'
    | '/pharmacy/$id'
    | '/report/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/clinics'
    | '/consultation'
    | '/forgot-password'
    | '/heatmap'
    | '/login'
    | '/medications'
    | '/mo'
    | '/onboarding'
    | '/pharmacy'
    | '/profile'
    | '/reset-password'
    | '/sos'
    | '/visits'
    | '/checkin/$token'
    | '/mo/$id'
    | '/pharmacy/$id'
    | '/report/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClinicsRoute: typeof ClinicsRoute
  ConsultationRoute: typeof ConsultationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HeatmapRoute: typeof HeatmapRoute
  LoginRoute: typeof LoginRoute
  MedicationsRoute: typeof MedicationsRoute
  MoRoute: typeof MoRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PharmacyRoute: typeof PharmacyRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SosRoute: typeof SosRoute
  VisitsRoute: typeof VisitsRoute
  CheckinTokenRoute: typeof CheckinTokenRoute
  ReportIdRoute: typeof ReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mo': {
      id: '/mo'
      path: '/mo'
      fullPath: '/mo'
      preLoaderRoute: typeof MoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/$id': {
      id: '/pharmacy/$id'
      path: '/$id'
      fullPath: '/pharmacy/$id'
      preLoaderRoute: typeof PharmacyIdRouteImport
      parentRoute: typeof PharmacyRoute
    }
    '/mo/$id': {
      id: '/mo/$id'
      path: '/$id'
      fullPath: '/mo/$id'
      preLoaderRoute: typeof MoIdRouteImport
      parentRoute: typeof MoRoute
    }
    '/checkin/$token': {
      id: '/checkin/$token'
      path: '/checkin/$token'
      fullPath: '/checkin/$token'
      preLoaderRoute: typeof CheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoRouteChildren {
  MoIdRoute: typeof MoIdRoute
}

const MoRouteChildren: MoRouteChildren = {
  MoIdRoute: MoIdRoute,
}

const MoRouteWithChildren = MoRoute._addFileChildren(MoRouteChildren)

interface PharmacyRouteChildren {
  PharmacyIdRoute: typeof PharmacyIdRoute
}

const PharmacyRouteChildren: PharmacyRouteChildren = {
  PharmacyIdRoute: PharmacyIdRoute,
}

const PharmacyRouteWithChildren = PharmacyRoute._addFileChildren(
  PharmacyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClinicsRoute: ClinicsRoute,
  ConsultationRoute: ConsultationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HeatmapRoute: HeatmapRoute,
  LoginRoute: LoginRoute,
  MedicationsRoute: MedicationsRoute,
  MoRoute: MoRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PharmacyRoute: PharmacyRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SosRoute: SosRoute,
  VisitsRoute: VisitsRoute,
  CheckinTokenRoute: CheckinTokenRoute,
  ReportIdRoute: ReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
